# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
