# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default='empty'),
        ),
    ]
